#!/bin/bash

docRoot=/var/www
htmlPart=html/$1
logPart=log/$1
apacheUser=apache:apache

hostDir=/vagrant
hostHtml=$hostDir/$htmlPart
hostLog=$hostDir/$logPart

htmlPath=$docRoot/$htmlPart
logPath=$docRoot/$logPart
httpdPath=/etc/httpd
sitesAvailablePath=$httpdPath/sites-available
configFile=$1.conf
siteConfig=$sitesAvailablePath/$configFile
hostHtmlPublicPath=$hostHtml/$3

if [ -z ${4} ]
then
    php=71
else
    php=$4
fi

mkdir -p $hostHtmlPublicPath
mkdir -p $hostLog

echo '<?php phpinfo(); ?>' > $hostHtmlPublicPath/index.php
echo '' > $hostLog/access.log
echo '' > $hostLog/error.log

eval "echo \"$(cat /vagrant/templates/v-host.tpl)\"" > $siteConfig
sudo ln -s $siteConfig $httpdPath/sites-enabled/$configFile
sudo chown $apacheUser -R $htmlPath
sudo chown $apacheUser -R $logPath
sudo setenforce 0
sudo server-restart
