#!/bin/bash

phpVersion=71

if [ -z ${1} ]
then
echo "Set php version"
exit
fi

if [ $1 == 5 ]
then
phpVersion=56
fi

sudo update-alternatives --set php /opt/remi/php$phpVersion/root/usr/bin/php

echo "php changed to php"$phpVersion
