#!/bin/bash

phpVersion=71
phpPath=/usr/bin/php

if [ -z ${1} ]
then
echo "Set php version"
exit
fi

if [ $1 == 5 ]
then
phpVersion=56
fi

sudo update-alternatives --set php $phpPath$phpVersion

echo "php changed to "$phpPath$phpVersion
